print((lambda x: {len(k): sorted([v for v in x if len(v)==len(k)]) for k in x })(["hi", "yo", "cat", "bat", "python", "ok"]))
print((lambda x: {k: x.index(k) for k in set(list(x))})("banana"))
print((lambda x: {k: {ke: x.count(ke) for ke in x if ke[0]==k} for k in set(map(lambda y: y[0], x))})(["apple", "ant", "banana", "bat", "apple", "ant", "bat"]))
print((lambda x: {k: k*k for k in list(map(int, x))})(input("Enter integers: ").split(" ")))
print((lambda x: {k: x.count(k) for k in set(x)})(input("Enter: ").lower().split(" ")))
print((lambda x: {k: [v for v in range(len(x)) if x[v]==k] for k in set(x)})(list(map(int, input("Enter a list: ").split(" ")))))
print((lambda x: sorted([i for i in set(x) if x.count(i) == max(x.count(k) for k in set(x))])[0])(list(map(int, (input("Enter a list: ").split(" "))))))
print((lambda x: sum(k for k in x if k%2==0))(list(map(int, input("Enter a list: ").split(" ")))))
print((lambda x: True if len([i for i in x if i==i[::-1]]) else False)(input("Enter a list: ").split(" ")))
print((lambda x: [i for i in x if len([k for k in range(1, i-1) if i%k==0])==1])(list(map(int, (input("Enter a list: ").split(" "))))))
print((lambda x: max(list(map(str, [len(i) for i in x])), key=list(map(str, [len(i) for i in x])).count))(input("Enter a list: ").split(" ")))
print(sorted(list(map(int, input("Enter 1st: ").split(" ")))+list(map(int, input("Enter 2nd: ").split(" ")))))
print((lambda x,y: x[y:]+x[:y])((input("Enter a list: ").split(" ")), int(input("Enter an integer: "))))
print((lambda x: max(x, key=len))(input("Enter a list: ").split(" ")))
print((lambda x: (lambda y: all(((y.append(i) or True) if i in "{[(" else ((y.pop() or False) if ({"(":")","{":"}","[":"]"}[y[-1]]==i) else None) for i in x)))([]))(list("({}[])")))
print((lambda x: (lambda y: [y.append(i) for i in x if not i in y] and y)([]))([1, 2, 3, 2, 4, 3, 5]))
print((lambda x: (lambda y:[sum([y, int(x[i-1]), int(x[i+1])]) and [x.pop(k) for k in range(0, i)] if x[i] =="+" else (abs(y - int(x[i-1])-int(x[i])) and [x.pop(k) for k in range(0, i)] if x[i+1]=="-" else None) for i in range(1, len(x)-1)])(0))(list("2+3-1")))
print((lambda x:   ((lambda y: y.append(x[i+1:x.index("-", i+1)-1]) for i in range(len(x)) if x[i] == "-" or y)([]),   (lambda z: (z.append(x[i+1:x.index("-", i+1)-1]) for i in range(len(x)) if x[i] == "-" or z)([]))  )   )(list("2+3-1")))
lis=["1", "+", "2", "-", "3"]
lis.pop(lis.index("1"):lis.index("2")+1)
print(lis)
print((lambda x, y: [i for i in x for k in range(y)])(input("Gimme list: ").split(", "), int(input("Give me an integer: "))))
print((lambda x: [eval(i) for i in x])(input("Give me a list: ").split("; ")))
print((lambda a, b:[a[i] for i in range(len(min(a, b))) if a[i]==b[i]])([1,2,3,4], [1,5,3,7]))
print((lambda a, b: '-'.join([i for i in a+b]))(list("abc"), list("defgh")))
print((lambda a, b: ''.join([a[i]+b[i].upper() for i in range(len(min(a, b, key=len)))] + [a, b][len(b)>len(a)][len(min(a, b, key=len)):]))(list("hello"), list("WORLDDDS")))
print((lambda a, b: dict(zip(a, b)))(list("abcd"), list("1233")))
print((lambda x: {k:v*1.1 for k,v in x.items()})({'apple': 1.2, 'banana': 0.8, 'orange': 1.5}))
print((lambda x: {k: x[k] for k in range(len(x))})([[1, 2], [3, 4], [5, 6]]))
print((lambda x: {x[k]: x[k+1] for k in range(len(x)) if x[k] != " " and x[k] not in "0123456789"})(list("a1 b2 c3 d4")))
print((lambda x: {k.split(":")[0]: [v.split(":")[1] for v in x if v.split(":")[0]==k.split(":")[0]] for k in x})(["Alice:85", "Bob:90", "Alice:78", "Charlie:92", "Bob:88"]))
print((lambda x, y: {k: y.append(str(x[k])) or y.copy() if x[k].isnumeric() else (y.append(sum([int(y.pop()), int(y.pop())])) or y.copy() if x[k]=="+" else (y.append(int(y.pop())*int(y.pop())) or y.copy() if x[k]=="*" else y.append(abs(int(y.pop())-int(y.pop()))) or y.copy())) for k in range(len(x))} )("3 4 + 2 * 5 -".split(" "), []))
print((lambda x, y: {kind:{"password": x[kind], "changes": y.append(f"{'+' if len(x[kind-1])<len(x[kind]) else '-'}{x[kind][len(x[kind-1]):] if len(x[kind-1])<len(x[kind]) else x[kind-1][len(x[kind]):]}") or y.copy() if kind!=0 else y.copy(), "valid": len(x[kind])>=4} for kind in range(len(x))})(["abc", "abcdd", "abc", "ab", "abc"], []))

